variable_shipping_custom_price:
    path: /variable-shipping/custom-price
    methods: [POST]
    defaults:
        _controller: 'cdigruttola\Module\VariableShipping\Controller\VariableShippingController::customPrice'
